# Generated by Django 5.2.14 on 2026-05-31 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_number", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "vessel_type",
                    models.CharField(
                        choices=[
                            ("new_build", "New Build"),
                            ("repair", "Repair"),
                            ("maintenance", "Maintenance"),
                            ("conversion", "Conversion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ship_type",
                    models.CharField(
                        choices=[
                            ("tugboat", "Tugboat"),
                            ("cargo", "Cargo Ship"),
                            ("tanker", "Tanker"),
                            ("barge", "Barge"),
                            ("ferry", "Ferry"),
                            ("fishing", "Fishing Vessel"),
                            ("patrol", "Patrol Boat"),
                            ("dredger", "Dredger"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("in_progress", "In Progress"),
                            ("testing", "Testing"),
                            ("completed", "Completed"),
                            ("delivered", "Delivered"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vessels",
                        to="clients.client",
                    ),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_vessels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VesselPart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("part_number", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.IntegerField(default=1)),
                ("unit", models.CharField(default="pcs", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ordered", "Ordered"),
                            ("received", "Received"),
                            ("installed", "Installed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="vessels.vessel",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VesselSpec",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "beam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "draft",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "gross_ton",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "deadweight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("engine_type", models.CharField(blank=True, max_length=100)),
                ("horsepower", models.IntegerField(blank=True, null=True)),
                (
                    "speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="knots",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("capacity", models.CharField(blank=True, max_length=100)),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Steel, Aluminum, Fiberglass",
                        max_length=100,
                    ),
                ),
                ("class_notation", models.CharField(blank=True, max_length=100)),
                (
                    "vessel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec",
                        to="vessels.vessel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
